name: Publish snapshot to SciJava Maven

on: 
  - push
  - workflow_dispatch

jobs:
  jars:
    name: Build jars
    uses: ./.github/workflows/jars.yml
  publish:
    needs: jars

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v4

    - name: Debug
      shell: bash
      run: |
        tree .

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'

    # - name: Validate Gradle wrapper
    #   uses: gradle/wrapper-validation-action@v1


    # - name: Publish snapshot
    #   uses: gradle/gradle-build-action@v2
    #   with:
    #     arguments: publish
    #   env:
    #     MAVEN_USER: ${{ secrets.MAVEN_USER }}
    #     MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
